CREATE TABLE tab_PlayerScoreData(
	fId INT NOT NULL IDENTITY(1,1),
	frFixtureId INT NOT NULL,
	frPlayerId INT NOT NULL,
	fTotalPoints INT,
	fMinutesPlayed INT,
	fGoalsScored INT,
	fAssists INT,
	fCleanSheet BIT,
	fShotsSaved INT,
	fPenaltiesSaved INT,
	fPenaltiesMissed INT,
	fGoalsConceded INT,
	fYellowCards INT,
	fRedCard INT,
	fOwnGoals INT,
	fLastUpdatedUtc DATETIME,
	PRIMARY KEY (fId),
	FOREIGN KEY (frFixtureId) REFERENCES tab_FixtureData(fId),
	FOREIGN KEY (frPlayerId) REFERENCES tab_PlayerStaticData(fId)
);